default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  password: 9419196

development:
  <<: *default
  database: "development_lifestyle-capstone"

test:
  <<: *default
  database: "test_lifestyle-capstone"

production:
  <<: *default
  database: "production_lifestyle-capstone"